Repository 25-Gachon-MobileProgramming/EmoTa-Diary, pull requests merged in 2025-05, with the labels that each got.

#38 Fix manifest typo
  app/src/main/AndroidManifest.xml
Labels: bug

#45 Fix typo in MainActivity
  app/src/main/java/kr/co/gachon/emotion_diary/MainActivity.java
Labels: bug

#40 Feature/#29 change db structure with emotions
  app/src/main/java/kr/co/gachon/emotion_diary/data/AppDatabase.java
  app/src/main/java/kr/co/gachon/emotion_diary/data/Diary.java
  app/src/main/java/kr/co/gachon/emotion_diary/data/DiaryDao.java
  app/src/main/java/kr/co/gachon/emotion_diary/data/DiaryRepository.java
  app/src/main/java/kr/co/gachon/emotion_diary/data/EmotionCount.java
  app/src/main/java/kr/co/gachon/emotion_diary/data/Emotions.java
Labels: enhancement

#52 Fix Code Intent, Manifest.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/gachon/emotion_diary/MainActivity.java
  app/src/main/java/kr/co/gachon/emotion_diary/data/AppDatabase.java
  app/src/main/java/kr/co/gachon/emotion_diary/data/Diary.java
  app/src/main/java/kr/co/gachon/emotion_diary/ui/OnBoarding/AvatarActivity.java
  app/src/main/java/kr/co/gachon/emotion_diary/ui/Remind/WriteRate/CircleGraphView.java
  app/src/main/java/kr/co/gachon/emotion_diary/ui/Remind/WriteRate/RateActivity.java
  app/src/main/java/kr/co/gachon/emotion_diary/ui/Remind/remindSummary/RemindSummary.java
  app/src/main/java/kr/co/gachon/emotion_diary/ui/Remind/timeGraph/TimeGraph.java
  app/src/main/java/kr/co/gachon/emotion_diary/ui/Remind/timeGraph/TimeZoneActivity.java
  app/src/main/java/kr/co/gachon/emotion_diary/ui/answerPage/AnswerActivity.java
  app/src/main/java/kr/co/gachon/emotion_diary/ui/emotion/EmotionSelectActivity.java
  app/src/main/java/kr/co/gachon/emotion_diary/ui/myPage/MyPageFragment.java
  app/src/main/java/kr/co/gachon/emotion_diary/ui/timeLine/MonthlyDiaryAdapter.java
  app/src/main/java/kr/co/gachon/emotion_diary/ui/writePage/DiaryWriteActivity.java
  gradle/libs.versions.toml
Labels: fix

#65 Redesign write fab in main screen
  app/src/main/java/kr/co/gachon/emotion_diary/MainActivity.java
  app/src/main/res/drawable/pencil_outline.xml
  app/src/main/res/drawable/write_icon.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: refactor

#77 Fix/#67 emotion button
  app/src/main/java/kr/co/gachon/emotion_diary/ui/emotion/EmotionSelectActivity.java
  app/src/main/res/drawable/angry.png
  app/src/main/res/drawable/happy.png
  app/src/main/res/drawable/sad.png
  app/src/main/res/drawable/tired.png
  app/src/main/res/layout/activity_diary_emotion.xml
  app/src/main/res/values/colors.xml
Labels: fix

#100 feat diary network check
  app/src/main/java/kr/co/gachon/emotion_diary/data/Diary.java
  app/src/main/java/kr/co/gachon/emotion_diary/data/DiaryRepository.java
  app/src/main/java/kr/co/gachon/emotion_diary/helper/Helper.java
  app/src/main/java/kr/co/gachon/emotion_diary/ui/answerPage/AnswerActivity.java
  app/src/main/java/kr/co/gachon/emotion_diary/ui/emotion/EmotionSelectActivity.java
  app/src/main/java/kr/co/gachon/emotion_diary/ui/taro/TaroActivity.java
  app/src/main/java/kr/co/gachon/emotion_diary/ui/writePage/DiaryWriteActivity.java
Labels: enhancement
